### ISSUE TITLE
可以提供一下靶场吗

### ISSUE THREAD

**Issue by littlebin404** [G-Security-Team/JS-Forward#1]
师傅，可以提供一下测试该脚本工具的靶场吗

**Comment by lijiaxing1997** [comment]
这个随意找个呗，我也忘记地址了

**Comment by lijiaxing1997** [comment]
老早写的了

**Comment by aa506** [comment]
> 师傅，可以提供一下测试该脚本工具的靶场吗

可以使用c0ny1师傅提供的靶场环境，https://github.com/c0ny1/jsEncrypter/tree/master/test/webapp
