### ISSUE TITLE
将payload插入进要替换参数的位置

### ISSUE THREAD

**Issue by UIWP0** [G-Security-Team/JS-Forward#2]
1、将payload插入进要替换参数的位置，是将payload替换加密函数中每一个变量？还是将函数内所有代码替换成payload？
例如如下代码，我是将函数中所有的变量val 替换成生成的payload？（假如函数中有多个val变量）
`
function aes(val) {
    var k = CryptoJS.enc.Utf8.parse('1234567890abcDEF');
    var iv = CryptoJS.enc.Utf8.parse('1234567890abcDEF');
    enc = CryptoJS.AES.encrypt($.trim(val), k, {iv: iv, mode:CryptoJS.mode.CBC, padding: CryptoJS.pad.ZeroPadding}).toString();
    return enc;
}`

2、若一个函数有多个参数，在生成payload时，是一起生成，还是单个生成？

**Comment by lijiaxing1997** [comment]
1、插入payload即可，并不是替换掉。`function aes(val) { 
生成的payload;
var k = CryptoJS.enc.Utf8.parse('1234567890abcDEF'); var iv = CryptoJS.enc.Utf8.parse('1234567890abcDEF'); enc = CryptoJS.AES.encrypt($.trim(val), k, {iv: iv, mode:CryptoJS.mode.CBC, padding: CryptoJS.pad.ZeroPadding}).toString(); return enc; }`

2、可以生成多个payload分别插入，也可以自己修改payload达到一起转发出来的效果。
